# Generated by Django 4.1.2 on 2023-05-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Category_title')),
                ('slug', models.SlugField(max_length=55, verbose_name='Category_slug')),
                ('description', models.TextField(blank=True, verbose_name='Category_description')),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Category_image')),
                ('is_active', models.BooleanField(verbose_name='Is_active')),
                ('is_featured', models.BooleanField(verbose_name='Is_featured')),
            ],
        ),
    ]
