# Generated by Django 4.1.2 on 2023-05-09 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Product title')),
                ('slug', models.SlugField(max_length=150, verbose_name='Product slug')),
                ('description', models.TextField(blank=True, verbose_name='Product description')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Product image')),
                ('product_stock', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(verbose_name='Is active')),
                ('is_featured', models.BooleanField(verbose_name='Is featured')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.category', verbose_name='product categoy')),
            ],
        ),
    ]
